apiVersion: v1
kind: PersistentVolume
metadata:
  name: kittens-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/kittens-local-volume
    # worker-node içerisindeki klasör adı: kittens-local-volume
    # Daha önceden bu klasör oluşturmamış olsan da kendisi oluşacak